<a href="https://colab.research.google.com/github/azrapatvi/next-word-prediction-lstm/blob/main/next_wod_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [54]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [55]:
#data collection
import nltk
nltk.download('gutenberg')
from nltk.corpus import gutenberg

data=gutenberg.raw('shakespeare-hamlet.txt')

data

[nltk_data] Downloading package gutenberg to /root/nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


"[The Tragedie of Hamlet by William Shakespeare 1599]\n\n\nActus Primus. Scoena Prima.\n\nEnter Barnardo and Francisco two Centinels.\n\n  Barnardo. Who's there?\n  Fran. Nay answer me: Stand & vnfold\nyour selfe\n\n   Bar. Long liue the King\n\n   Fran. Barnardo?\n  Bar. He\n\n   Fran. You come most carefully vpon your houre\n\n   Bar. 'Tis now strook twelue, get thee to bed Francisco\n\n   Fran. For this releefe much thankes: 'Tis bitter cold,\nAnd I am sicke at heart\n\n   Barn. Haue you had quiet Guard?\n  Fran. Not a Mouse stirring\n\n   Barn. Well, goodnight. If you do meet Horatio and\nMarcellus, the Riuals of my Watch, bid them make hast.\nEnter Horatio and Marcellus.\n\n  Fran. I thinke I heare them. Stand: who's there?\n  Hor. Friends to this ground\n\n   Mar. And Leige-men to the Dane\n\n   Fran. Giue you good night\n\n   Mar. O farwel honest Soldier, who hath relieu'd you?\n  Fra. Barnardo ha's my place: giue you goodnight.\n\nExit Fran.\n\n  Mar. Holla Barnardo\n\n   Bar. 

In [56]:
with open('data.txt','w')as f:
  f.write(data)

In [57]:
with open('data.txt','r')as f:
  text=f.read().lower()



In [58]:
text

"[the tragedie of hamlet by william shakespeare 1599]\n\n\nactus primus. scoena prima.\n\nenter barnardo and francisco two centinels.\n\n  barnardo. who's there?\n  fran. nay answer me: stand & vnfold\nyour selfe\n\n   bar. long liue the king\n\n   fran. barnardo?\n  bar. he\n\n   fran. you come most carefully vpon your houre\n\n   bar. 'tis now strook twelue, get thee to bed francisco\n\n   fran. for this releefe much thankes: 'tis bitter cold,\nand i am sicke at heart\n\n   barn. haue you had quiet guard?\n  fran. not a mouse stirring\n\n   barn. well, goodnight. if you do meet horatio and\nmarcellus, the riuals of my watch, bid them make hast.\nenter horatio and marcellus.\n\n  fran. i thinke i heare them. stand: who's there?\n  hor. friends to this ground\n\n   mar. and leige-men to the dane\n\n   fran. giue you good night\n\n   mar. o farwel honest soldier, who hath relieu'd you?\n  fra. barnardo ha's my place: giue you goodnight.\n\nexit fran.\n\n  mar. holla barnardo\n\n   bar. 

In [59]:
# keras tokenizer converts the text to numbers
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

# tokenize text
tokenizer=Tokenizer()
tokenizer.fit_on_texts([text]) # this basically reads the text ,finds all the unique words and assignseach eord a number .... and this assigns small numbers to most frequent words so that the word which are unique will be having large numbers
total_words=len(tokenizer.word_index)+1

total_words


4818

In [60]:
type(tokenizer.word_index)

dict

In [61]:
tokenizer.word_index #dictionary of words with there converted numbers

{'the': 1,
 'and': 2,
 'to': 3,
 'of': 4,
 'i': 5,
 'you': 6,
 'a': 7,
 'my': 8,
 'it': 9,
 'in': 10,
 'that': 11,
 'ham': 12,
 'is': 13,
 'not': 14,
 'his': 15,
 'this': 16,
 'with': 17,
 'your': 18,
 'but': 19,
 'for': 20,
 'me': 21,
 'lord': 22,
 'as': 23,
 'what': 24,
 'he': 25,
 'be': 26,
 'so': 27,
 'him': 28,
 'haue': 29,
 'king': 30,
 'will': 31,
 'no': 32,
 'our': 33,
 'we': 34,
 'on': 35,
 'are': 36,
 'if': 37,
 'all': 38,
 'then': 39,
 'shall': 40,
 'by': 41,
 'thou': 42,
 'come': 43,
 'or': 44,
 'hamlet': 45,
 'good': 46,
 'do': 47,
 'hor': 48,
 'her': 49,
 'let': 50,
 'now': 51,
 'thy': 52,
 'how': 53,
 'more': 54,
 'they': 55,
 'from': 56,
 'enter': 57,
 'at': 58,
 'was': 59,
 'oh': 60,
 'like': 61,
 'most': 62,
 'there': 63,
 'well': 64,
 'know': 65,
 'selfe': 66,
 'would': 67,
 'them': 68,
 'loue': 69,
 'may': 70,
 "'tis": 71,
 'vs': 72,
 'sir': 73,
 'qu': 74,
 'which': 75,
 'did': 76,
 'why': 77,
 'laer': 78,
 'giue': 79,
 'thee': 80,
 'ile': 81,
 'must': 82,
 'hath': 

In [62]:
reversed={value:key for key,value in tokenizer.word_index.items()}
reversed

{1: 'the',
 2: 'and',
 3: 'to',
 4: 'of',
 5: 'i',
 6: 'you',
 7: 'a',
 8: 'my',
 9: 'it',
 10: 'in',
 11: 'that',
 12: 'ham',
 13: 'is',
 14: 'not',
 15: 'his',
 16: 'this',
 17: 'with',
 18: 'your',
 19: 'but',
 20: 'for',
 21: 'me',
 22: 'lord',
 23: 'as',
 24: 'what',
 25: 'he',
 26: 'be',
 27: 'so',
 28: 'him',
 29: 'haue',
 30: 'king',
 31: 'will',
 32: 'no',
 33: 'our',
 34: 'we',
 35: 'on',
 36: 'are',
 37: 'if',
 38: 'all',
 39: 'then',
 40: 'shall',
 41: 'by',
 42: 'thou',
 43: 'come',
 44: 'or',
 45: 'hamlet',
 46: 'good',
 47: 'do',
 48: 'hor',
 49: 'her',
 50: 'let',
 51: 'now',
 52: 'thy',
 53: 'how',
 54: 'more',
 55: 'they',
 56: 'from',
 57: 'enter',
 58: 'at',
 59: 'was',
 60: 'oh',
 61: 'like',
 62: 'most',
 63: 'there',
 64: 'well',
 65: 'know',
 66: 'selfe',
 67: 'would',
 68: 'them',
 69: 'loue',
 70: 'may',
 71: "'tis",
 72: 'vs',
 73: 'sir',
 74: 'qu',
 75: 'which',
 76: 'did',
 77: 'why',
 78: 'laer',
 79: 'giue',
 80: 'thee',
 81: 'ile',
 82: 'must',
 83: 'hat

In [63]:
sample_word = 'wrong'

print(tokenizer.word_index.get(sample_word))

500


In [64]:
text

"[the tragedie of hamlet by william shakespeare 1599]\n\n\nactus primus. scoena prima.\n\nenter barnardo and francisco two centinels.\n\n  barnardo. who's there?\n  fran. nay answer me: stand & vnfold\nyour selfe\n\n   bar. long liue the king\n\n   fran. barnardo?\n  bar. he\n\n   fran. you come most carefully vpon your houre\n\n   bar. 'tis now strook twelue, get thee to bed francisco\n\n   fran. for this releefe much thankes: 'tis bitter cold,\nand i am sicke at heart\n\n   barn. haue you had quiet guard?\n  fran. not a mouse stirring\n\n   barn. well, goodnight. if you do meet horatio and\nmarcellus, the riuals of my watch, bid them make hast.\nenter horatio and marcellus.\n\n  fran. i thinke i heare them. stand: who's there?\n  hor. friends to this ground\n\n   mar. and leige-men to the dane\n\n   fran. giue you good night\n\n   mar. o farwel honest soldier, who hath relieu'd you?\n  fra. barnardo ha's my place: giue you goodnight.\n\nexit fran.\n\n  mar. holla barnardo\n\n   bar. 

In [65]:
# this is necessary step while create next word prediction

input_sequences = []

for line in text.split('\n'):
    token_list = tokenizer.texts_to_sequences([line])[0]

    for i in range(1, len(token_list)):
        n_gram_sequence = token_list[:i+1]
        input_sequences.append(n_gram_sequence)

input_sequences

[[1, 687],
 [1, 687, 4],
 [1, 687, 4, 45],
 [1, 687, 4, 45, 41],
 [1, 687, 4, 45, 41, 1886],
 [1, 687, 4, 45, 41, 1886, 1887],
 [1, 687, 4, 45, 41, 1886, 1887, 1888],
 [1180, 1889],
 [1180, 1889, 1890],
 [1180, 1889, 1890, 1891],
 [57, 407],
 [57, 407, 2],
 [57, 407, 2, 1181],
 [57, 407, 2, 1181, 177],
 [57, 407, 2, 1181, 177, 1892],
 [407, 1182],
 [407, 1182, 63],
 [408, 162],
 [408, 162, 377],
 [408, 162, 377, 21],
 [408, 162, 377, 21, 247],
 [408, 162, 377, 21, 247, 882],
 [18, 66],
 [451, 224],
 [451, 224, 248],
 [451, 224, 248, 1],
 [451, 224, 248, 1, 30],
 [408, 407],
 [451, 25],
 [408, 6],
 [408, 6, 43],
 [408, 6, 43, 62],
 [408, 6, 43, 62, 1893],
 [408, 6, 43, 62, 1893, 96],
 [408, 6, 43, 62, 1893, 96, 18],
 [408, 6, 43, 62, 1893, 96, 18, 566],
 [451, 71],
 [451, 71, 51],
 [451, 71, 51, 1894],
 [451, 71, 51, 1894, 567],
 [451, 71, 51, 1894, 567, 378],
 [451, 71, 51, 1894, 567, 378, 80],
 [451, 71, 51, 1894, 567, 378, 80, 3],
 [451, 71, 51, 1894, 567, 378, 80, 3, 273],
 [451, 71

In [66]:
for i in input_sequences:
  print(i)

[1, 687]
[1, 687, 4]
[1, 687, 4, 45]
[1, 687, 4, 45, 41]
[1, 687, 4, 45, 41, 1886]
[1, 687, 4, 45, 41, 1886, 1887]
[1, 687, 4, 45, 41, 1886, 1887, 1888]
[1180, 1889]
[1180, 1889, 1890]
[1180, 1889, 1890, 1891]
[57, 407]
[57, 407, 2]
[57, 407, 2, 1181]
[57, 407, 2, 1181, 177]
[57, 407, 2, 1181, 177, 1892]
[407, 1182]
[407, 1182, 63]
[408, 162]
[408, 162, 377]
[408, 162, 377, 21]
[408, 162, 377, 21, 247]
[408, 162, 377, 21, 247, 882]
[18, 66]
[451, 224]
[451, 224, 248]
[451, 224, 248, 1]
[451, 224, 248, 1, 30]
[408, 407]
[451, 25]
[408, 6]
[408, 6, 43]
[408, 6, 43, 62]
[408, 6, 43, 62, 1893]
[408, 6, 43, 62, 1893, 96]
[408, 6, 43, 62, 1893, 96, 18]
[408, 6, 43, 62, 1893, 96, 18, 566]
[451, 71]
[451, 71, 51]
[451, 71, 51, 1894]
[451, 71, 51, 1894, 567]
[451, 71, 51, 1894, 567, 378]
[451, 71, 51, 1894, 567, 378, 80]
[451, 71, 51, 1894, 567, 378, 80, 3]
[451, 71, 51, 1894, 567, 378, 80, 3, 273]
[451, 71, 51, 1894, 567, 378, 80, 3, 273, 1181]
[408, 20]
[408, 20, 16]
[408, 20, 16, 1895]
[408,

In [67]:
max_seq_len=max([len(i) for i in input_sequences])

max_seq_len

14

In [68]:
# pad_sequences
input_sequences=pad_sequences(input_sequences,maxlen=max_seq_len,padding='pre')
print(type(input_sequences))
print(input_sequences)

<class 'numpy.ndarray'>
[[   0    0    0 ...    0    1  687]
 [   0    0    0 ...    1  687    4]
 [   0    0    0 ...  687    4   45]
 ...
 [   0    0    0 ...    4   45 1047]
 [   0    0    0 ...   45 1047    4]
 [   0    0    0 ... 1047    4  193]]


In [69]:
# create predictors and labels
len(input_sequences[:,:-1])

25732

In [70]:
X=input_sequences[:,:-1]

In [71]:
input_sequences[:,:-1]

array([[   0,    0,    0, ...,    0,    0,    1],
       [   0,    0,    0, ...,    0,    1,  687],
       [   0,    0,    0, ...,    1,  687,    4],
       ...,
       [   0,    0,    0, ...,  687,    4,   45],
       [   0,    0,    0, ...,    4,   45, 1047],
       [   0,    0,    0, ...,   45, 1047,    4]], dtype=int32)

In [72]:
y=input_sequences[:,-1]

y

array([ 687,    4,   45, ..., 1047,    4,  193], dtype=int32)

In [73]:
total_words

4818

In [74]:
import tensorflow as tf

In [75]:
y=tf.keras.utils.to_categorical(y,num_classes=total_words) # this basically create number of total_words classes measn 4818 clases and will make 1 where evar the number gets found ex:687 so so at 687 index there will be 1 ->[0., 0.,0.,....,1.,0,0,...0]

y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [76]:
y[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [77]:
len(y[0])

4818

In [78]:
y[0][687]

np.float64(1.0)

In [79]:
# train test split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [80]:
X_train

array([[   0,    0,    0, ...,   81,  686,   28],
       [   0,    0,    0, ...,    0, 1806,  289],
       [   0,    0,    0, ...,   42, 1381,   29],
       ...,
       [   0,    0,    0, ...,    0,  346,   71],
       [   0,    0,    0, ...,    0,   74,   45],
       [   0,    0,    0, ...,   28,   17,   16]], dtype=int32)

In [81]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [82]:

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Embedding,LSTM,Dropout, Input,GRU

In [83]:

total_words

4818

In [84]:

# define the model
model=Sequential()

model.add(Input(shape=(max_seq_len-1,)))

model.add(Embedding(input_dim=total_words, output_dim=100))
 # this converts numbers to dense vector
# max_seq_len-1 because earlier we did splitting [1,2,3,4] / [5] like this n_gram_sequence
# Each word will be converted into a vector of size 100

model.add(LSTM(150,return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(100))
model.add(Dense(total_words,activation='softmax'))


#model compile
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 13, 100)        │       481,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_6 (LSTM)                   │ (None, 13, 150)        │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 13, 150)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_7 (LSTM)                   │ (None, 100)            │       100,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 4818)           │       486,618 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,219,418 (4.65 MB)

 Trainable params: 1,219,418 (4.65 MB)

 Non-trainable params: 0 (0.00 B)

In [85]:
from tensorflow.keras.callbacks import EarlyStopping

es=EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [86]:
# train model

history=model.fit(X_train,y_train,epochs=100,validation_data=(X_test,y_test),verbose=1,callbacks=[es])

Epoch 1/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.0325 - loss: 6.9152 - val_accuracy: 0.0336 - val_loss: 6.7054
Epoch 2/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.0390 - loss: 6.4798 - val_accuracy: 0.0424 - val_loss: 6.7692
Epoch 3/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 7s 11ms/step - accuracy: 0.0456 - loss: 6.3413 - val_accuracy: 0.0464 - val_loss: 6.8009
Epoch 4/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.0511 - loss: 6.2047 - val_accuracy: 0.0476 - val_loss: 6.8074
Epoch 5/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.0541 - loss: 6.0817 - val_accuracy: 0.0542 - val_loss: 6.8517
Epoch 6/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.0595 - loss: 5.9434 - val_accuracy: 0.0598 - val_loss: 6.8778


In [87]:
text="who's there and for it and who is this drinke hearing vnckle haue"

# tokenize
input_tokenize=tokenizer.texts_to_sequences([text])

#pad_sequences
input_pad=pad_sequences(input_tokenize,maxlen=max_seq_len-1,padding='pre')

#predict
preds = model.predict(input_pad)[0]
pos = np.random.choice(len(preds), p=preds)

for word,index in tokenizer.word_index.items():
  if index==pos:
    print(word)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 277ms/step
seruice


In [88]:
tokenizer

In [89]:
model.save('lstm_model.keras')

import pickle

with open('tokenizer.pkl','wb') as f:
  pickle.dump(tokenizer,f)


In [90]:
#GRU RNN
gru=Sequential()

gru.add(Input(shape=(max_seq_len-1,)))

gru.add(Embedding(input_dim=total_words, output_dim=100))

gru.add(GRU(150,return_sequences=True))
gru.add(Dropout(0.2))
gru.add(LSTM(100))
gru.add(Dense(total_words,activation='softmax'))


#model compile
gru.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

gru.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ (None, 13, 100)        │       481,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_3 (GRU)                     │ (None, 13, 150)        │       113,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 13, 150)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_8 (LSTM)                   │ (None, 100)            │       100,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 4818)           │       486,618 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,182,218 (4.51 MB)

 Trainable params: 1,182,218 (4.51 MB)

 Non-trainable params: 0 (0.00 B)

In [91]:
# train model

history=gru.fit(X_train,y_train,epochs=100,validation_data=(X_test,y_test),verbose=1,callbacks=[es])

Epoch 1/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step - accuracy: 0.0333 - loss: 6.9248 - val_accuracy: 0.0336 - val_loss: 6.6799
Epoch 2/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.0409 - loss: 6.4689 - val_accuracy: 0.0431 - val_loss: 6.7414
Epoch 3/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.0494 - loss: 6.2846 - val_accuracy: 0.0484 - val_loss: 6.7533
Epoch 4/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.0558 - loss: 6.1088 - val_accuracy: 0.0528 - val_loss: 6.8204
Epoch 5/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.0643 - loss: 5.9614 - val_accuracy: 0.0593 - val_loss: 6.8391
Epoch 6/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.0729 - loss: 5.8275 - val_accuracy: 0.0641 - val_loss: 6.9222


In [92]:
text="who's there"

# tokenize
input_tokenize=tokenizer.texts_to_sequences([text])

#pad_sequences
input_pad=pad_sequences(input_tokenize,maxlen=max_seq_len-1,padding='pre')

#predict
preds = gru.predict(input_pad)[0]
pos = np.random.choice(len(preds), p=preds)

for word,index in tokenizer.word_index.items():
  if index==pos:
    print(word)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 174ms/step
it
